### PR TITLE
Unit test

### PR DESCRIPTION
**Pull request by chudisoft**
**[Project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md#project-requirements)**
**Add the following validations:**

- For the User model:
- Name must not be blank.
- PostsCounter must be an integer greater than or equal to zero.
- For the Post model:

- [ ] Title must not be blank.
- [ ] Title must not exceed 250 characters.

- CommentsCounter must be an integer greater than or equal to zero.
- LikesCounter must be an integer greater than or equal to zero.
- Add unit specs for all of your models' methods and validations.

### CODE REVIEW

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi @chudisoft 🙋‍♀️,  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted a project that does not fulfill a few requirements for a professional README.

- Kindly make sure that you do not have empty sections that do not have the relevant content. If a project is not deployed, please remove the `Live Demo` and the `Presentation Video` sections since they won't be used in this project.
- Kindly make sure that the content is relevant to the project. The project description states that this is a React and Redux project and that the features include selecting a categroy of music.

image

- The `Tech Stack` client should be updated and techs like react and redux should be removed since you won't be using them on this project.

- The `Getting Started` section should have commands on how to setup and run the project locally. Under `Install` you should have something like `bundle install` and under `Usage` include comands like `rails db:setup` or `rails db:create and db:migrate`, and `rails server`.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @chudisoft, you are still missing the future features section in your readme, this is a comment not a review 👍🏿

**Comment by chudisoft** [comment]
> Hi @chudisoft, you are missing the future features section in your readme, this is a comment not a review 👍🏿  

Updated

**Review by prolajumokeoni — APPROVED** [review]
- Sere summar below ⬇️

**Review by prolajumokeoni — COMMENTED** [review]
Hi @chudisoft 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters running, please ensure that your linters are running 👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @chudisoft 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters running, please ensure that your linters are running 👍🏿 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi @chudisoft 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ ❌ 

You have submitted a project, where your last commit doesn't have a green check mark 👀

image

According to the [general requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md#general-requirements)
- Linter should be set up correctly for this repository.
- Linter result should be green, this means that the last commit have a green check mark (✅) or a summary of the passed checks is in the PR.
- There should be no custom changes to linter config.

Please correct that 🤗🛠

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by chudisoft** [comment]
> Hi @chudisoft 🙋‍♂️,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request ❌ ❌ ❌
> You have submitted a project, where your last commit doesn't have a green check mark 👀
> 
> image
> 
> According to the [general requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_validations_model_spec.md#general-requirements)
> 
> * Linter should be set up correctly for this repository.
> * Linter result should be green, this means that the last commit have a green check mark (✅) or a summary of the passed checks is in the PR.
> * There should be no custom changes to linter config.
> 
> Please correct that 🤗🛠
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

image

Next time don't just invalidate someone@prolajumokeoni s project for no reason! @prolajumokeoni

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @chudisoft       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  . 
Congratulations! 🎉  Keep up the Awesome work 🥂  Keep Rocking 🥇 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Professional README file  
- [x] App runs as intended 






 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]

**Pull request merged**
